name: Multi-Platform Release

on:
  push:
    tags: ['v*']
permissions:
  contents: write
  packages: write
  actions: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="Release $TAG_NAME"
        BODY="## Multi-Platform Release

        This release includes binaries for:
        - Linux (x86_64)
        - Windows (x86_64)
        - macOS (x86_64)

        Download the appropriate binary for your platform."
        
        gh release create "$TAG_NAME" \
          --title "$RELEASE_NAME" \
          --notes "$BODY" \
          --latest

  build:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: verascan
            asset_name: verascan-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: verascan.exe
            asset_name: verascan-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: verascan
            asset_name: verascan-macos-amd64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: ${{ matrix.target }}
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        gh release upload "$TAG_NAME" \
          target/${{ matrix.target }}/release/${{ matrix.artifact_name }}#${{ matrix.asset_name }}
