name: Multi-Platform Release

on:
  push:
    tags: ['v*']
permissions:
  contents: write
  packages: write
  actions: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="Release $TAG_NAME"
        BODY="## Multi-Platform Release

        This release includes binaries for:
        - Linux (x86_64)
        - Windows (x86_64)
        - macOS (x86_64)

        Download the appropriate binary for your platform."
        
        gh release create "$TAG_NAME" \
          --title "$RELEASE_NAME" \
          --notes "$BODY" \
          --latest

  build:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            archive: zip
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Release
      uses: rust-build/rust-build.action@v1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        ARCHIVE_TYPES: ${{ matrix.archive }}
